"""Tests that keep the standards record truthful.

``docs/standards/`` is where this package makes its compliance claims.
A claim nobody checks is a claim that drifts, so these tests run the
same validation CI runs, and additionally verify that the tests named
in ``requirements.json`` actually exist and pass collection.

The network hash check is *not* run here — it lives in a separate CI
job so that an offline test run still works.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
STANDARDS = REPO_ROOT / "docs" / "standards"
SCRIPT = REPO_ROOT / "scripts" / "check_standards.py"


@pytest.fixture(scope="module")
def requirements() -> dict:
    with (STANDARDS / "requirements.json").open(encoding="utf-8") as fh:
        return json.load(fh)


@pytest.fixture(scope="module")
def manifest() -> dict:
    with (STANDARDS / "manifest.json").open(encoding="utf-8") as fh:
        return json.load(fh)


class TestStandardsRecord:
    def test_check_script_passes(self):
        """Structure is valid and coverage.md is up to date."""
        result = subprocess.run(
            [sys.executable, str(SCRIPT)],
            capture_output=True,
            text=True,
            cwd=REPO_ROOT,
        )
        assert result.returncode == 0, result.stderr

    def test_coverage_is_generated_not_handwritten(self):
        text = (STANDARDS / "coverage.md").read_text(encoding="utf-8")
        assert "Generated by scripts/check_standards.py" in text

    def test_every_pinned_standard_records_provenance(self, manifest):
        for std in manifest["standards"]:
            assert std["source_url"].startswith("https://")
            assert std["retrieved_at"].endswith("Z")
            assert std["license"]
            if std["sha256"] is not None:
                assert len(std["sha256"]) == 64
            else:
                assert std.get("note"), f"{std['id']} is unpinned without a note"

    def test_non_claims_are_documented(self, requirements):
        """Every unimplemented clause must say why, so the gap is a
        decision on the record rather than an omission."""
        unimplemented = [r for r in requirements["requirements"] if not r["implemented"]]
        assert unimplemented, "the profile claims total coverage; verify that"
        for req in unimplemented:
            assert req["reason"].strip()

    def test_named_test_targets_exist(self, requirements):
        """A requirement may not point at a test that was renamed away."""
        for req in requirements["requirements"]:
            for target in req.get("tests") or []:
                path, _, node = target.partition("::")
                file = REPO_ROOT / path
                assert file.is_file(), f"{req['id']} names missing {path}"
                if node:
                    source = file.read_text(encoding="utf-8")
                    name = node.split("::")[0]
                    assert f"class {name}" in source or f"def {name}" in source, (
                        f"{req['id']} names missing test target {target}"
                    )

    def test_readme_lists_the_non_claims(self, requirements):
        """The prose profile and the machine-readable map must agree."""
        readme = (STANDARDS / "README.md").read_text(encoding="utf-8")
        assert "What this package does not claim" in readme
        for req in requirements["requirements"]:
            if not req["implemented"]:
                keyword = req["clause"].split()[0].lower()
                assert keyword in readme.lower(), (
                    f"{req['id']} ({req['clause']}) is not mentioned in the standards README"
                )
